# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Diego García González
title: Computer Engineering Student
email: diego.garcia2084@alumnos.udg.mx
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username:  Diego-Ga-Glez
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: Diego-Ga-Glez
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
# additional_links:
# - title:
#   icon: 
#   url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Diego, I am a computer engineering student in the last year of my degree. I have been studying computer science
  for nearly 9 years, during that time I have engaging in numerous projects that have enabled me to develop both soft and technical 
  skills. Notably, I have developed strong competencies in teamwork, adaptability, and self-learning.

  In terms of programming, I am skilled in several languages, including <mark>Python</mark>, <mark>JavaScript</mark>, <mark>PHP</mark>, <mark>SQL</mark> and <mark>C/C++</mark>.

content:

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border:       # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Votting App
        link:
        link_text:
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/diana-castillo/Proy-ft
        quote: >
          Survey about Dogs vs Cats
        description: | # this will include new lines to allow paragraphs
          This project was developed for a fault tolerance class and implemented a microservices architecture. It was created and deployed in a sandbox 
          environment on Red Hat OpenShift. The project is a web application for answering and viewing the result of a simple survey. Each microservice
          was developed using multiple technologies, including <mark>Node.js</mark>, <mark>Python</mark>, <mark>JavaScript</mark> and <mark>PostgreSQL</mark>.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Reso Tisanas SA de CV
        sub_title: Full stack Developer
        caption: August 2023 - present
        link: lucinatisanas.com
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I have been working as a part-time full stack developer, responsible for updating and implementing new features on the company's 
          websites. My daily tasks involve working with <mark>PHP</mark>, <mark>JavaScript</mark> and <mark>MySQL</mark>. Besides, I troubleshoot
          and resolve issues related to the web hosting service utilized by the company.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad de Guadalajara
        sub_title: Bachelor in Computer Engineering
        caption: 2019 - present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          During my time at Universidad de Guadalajara, I deepened my understanding of programming by exploring 
          web and desktop development. Besides, I acquired basic knowledge about topics such as artificial intelligence, 
          cloud computing and related technologies. Likewise, I gained valuable experience with tools for collaborative
           code development.

      - layout: left
        title: Escuela Politécnica de Guadalajara
        sub_title: Professional Technologist in Computer Systems
        caption: 2015 - 2019
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          During my time at Escuela Politécnica de Guadalajara, I learned a solid foundation in programming
          covering essential topics such as data types, loops, conditionals, functions and object-oriented 
          programming through console application. Additionally, I gained basic knowledge of networking and 
          security principles through a Cisco course.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my interest in software engineering, I enjoy doing activities such as working out, 
      exploring new place to eat and gaming. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
